### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aqw** [BuckyMaler/apollo#1]
I really like this template, and would like to lift a few ideas from it for a website I'm building. However, I can't find a license file...

Could you please clarify whether you do indeed intend for this code to be All Rights Reserved or if it's freely licensed?

Thanks for your time, and thanks for sharing this template. :-)

---Alex

**Comment by BuckyMaler** [comment]
I'm glad you like the template. It's unlicensed, use it freely.

**Comment by BuckyMaler** [comment]
@aqw good to know. Feel free to create a pull request with an appropriate license. I've used the MIT license before, it would make sense for this project as well. I'll reopen this issue for the time being.
